// GETTERS
export const GET_USER_LOGGED_IN = "global_GET_USER_LOGGED_IN";
export const GET_USER_ACCESS_TOKEN = "global_GET_USER_ACCESS_TOKEN";

// MUTATORS
export const MUTATE_USER_LOGGED_IN = "global_MUTATE_USER_LOGGED_IN";
export const MUTATE_USER_ACCESS_TOKEN = "global_MUTATE_USER_ACCESS_TOKEN";